#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

MODE=${1:-setup}
RESULT_FILE=${2:-}
OUTCOME=failed
umask 077
complete_guide() {
    local code=$?
    trap - EXIT
    if [[ -n "$RESULT_FILE" ]]; then
        printf '%s\n' "$OUTCOME" > "$RESULT_FILE.tmp"
        /bin/mv "$RESULT_FILE.tmp" "$RESULT_FILE"
    fi
    if [[ "$OUTCOME" == failed ]]; then
        say "The change was not verified. Frog will check the actual permissions again."
        pause "Review the error above. Press Enter to close this guide."
    else
        say "This setup window will close automatically."
        /bin/sleep 2
    fi
    exit "$code"
}
trap complete_guide EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP

check_access() {
    local value listing
    for value in 0 1; do
        # -k ignores any cached admin login; -ll lists the effective matching
        # policy without executing the command or asking for a password.
        listing=$(/usr/bin/sudo -n -k -ll /usr/bin/pmset -a disablesleep "$value") || return 1
        printf '%s\n' "$listing" | /usr/bin/awk '
            /^[[:space:]]*Options:/ {
                found = 1
                if ($0 !~ /(^|[[:space:],])!authenticate([[:space:],]|$)/ ||
                    $0 ~ /(^|[[:space:],])authenticate([[:space:],]|$)/) bad = 1
            }
            END { exit !(found && !bad) }
        ' || return 1
    done
}

[[ "$(uname -s)" == Darwin ]] || { say "This setup is for macOS."; exit 1; }
[[ "$(id -u)" != 0 ]] || { say "Run this guide as your normal Mac user, not as root."; exit 1; }
[[ "$MODE" == setup || "$MODE" == reset ]] || { say "Use setup or reset."; exit 1; }
ACCOUNT=$(id -un)
[[ "$ACCOUNT" =~ ^[a-zA-Z_][a-zA-Z0-9_.-]*$ ]] || { say "Use visudo manually for this account name."; exit 1; }
RULE="$ACCOUNT ALL=(root) NOPASSWD: /usr/bin/pmset -a disablesleep 0, /usr/bin/pmset -a disablesleep 1"
RULE_FILE=/etc/sudoers.d/frog-awake

if [[ "$MODE" == reset ]]; then
    stage "What resetting access does"
    say "Frog restores sleep before opening this guide."
    say "This reset empties only $RULE_FILE, removing the rules in that dedicated Frog file."
    say "It does not edit the main sudoers file. Set up access again whenever you need the feature."
    step "sudo /usr/bin/tee $RULE_FILE < /dev/null"
    say "Your administrator password goes directly to sudo in Terminal, never Frog."
    confirm "Reset stay-awake access?" || { OUTCOME=cancelled; exit 0; }

    stage "Clear Frog's access file"
    if ! /usr/bin/pmset -g | /usr/bin/awk '
        $1 == "SleepDisabled" || $1 == "disablesleep" { if ($2 != "0") exit 1 }
    '; then
        say "Turn off Stay awake before resetting access, then try again."
        exit 1
    fi
    if /usr/bin/sudo /bin/test -f "$RULE_FILE"; then
        /usr/bin/sudo /usr/bin/tee "$RULE_FILE" < /dev/null > /dev/null
    fi

    stage "Verify the reset"
    /usr/bin/sudo /usr/sbin/visudo -c
    /usr/bin/sudo /bin/test ! -s "$RULE_FILE"
    finish
    say "Frog's access file is now empty. Sleep is allowed."
    if check_access 2>/dev/null; then
        say "Another sudoers rule still allows the power commands; Frog will show their actual availability."
    else
        say "Passwordless stay-awake access is removed. Frog Settings will show Setup needed."
    fi
    OUTCOME=success
    exit 0
fi

stage "Allow two power commands"
say "This guide adds a rule in $RULE_FILE, then verifies both commands without changing sleep."
say "The rule lets Frog turn the system-wide sleep setting on and off when you use Stay awake."
say "This permits only these exact commands, without a password prompt:"
step "/usr/bin/pmset -a disablesleep 0"
step "/usr/bin/pmset -a disablesleep 1"
say "Your admin password is entered directly into sudo in Terminal. Frog never receives it."
say "Setup does not turn Stay awake on. Lock your Mac separately before closing the lid."
say "After successful verification, Frog updates its status and this setup window closes automatically."
confirm "Configure this for $ACCOUNT?" || { OUTCOME=cancelled; exit 0; }

stage "Add the rule with visudo"
say "Add this one line to $RULE_FILE (keep any existing lines):"
say "If this exact line is already there, leave it unchanged."
printf '\n%s\n\n' "$RULE"
say "In the default vi editor: press i, paste the line, press Esc, type :wq, then Enter."
say "visudo checks the syntax before saving. To cancel in vi: Esc, :q!, Enter."
pause "Press Enter to open the editor."
/usr/bin/sudo /bin/mkdir -p /etc/sudoers.d
/usr/bin/sudo /usr/sbin/visudo -f "$RULE_FILE"

stage "Verify access without changing sleep"
/usr/bin/sudo /usr/sbin/visudo -c
if ! /usr/bin/sudo /usr/bin/grep -Fx "$RULE" "$RULE_FILE" >/dev/null; then
    say "The expected rule was not saved. Re-run this guide to add it."
    exit 1
fi
if ! check_access; then
    say "Both commands must be allowed without a password. Review the rule and run setup again."
    exit 1
fi
finish
say "Added and verified the two passwordless power permissions in $RULE_FILE."
say "Your Mac's sleep setting was not changed. Frog is ready to use the feature."
say "Open Frog's menu-bar popup and turn on Stay awake when you need it."
say "Default session: four hours. Frog restores sleep on quit or below 20% battery when unplugged."
say "You can check or reset this permission in Frog Settings → Stay awake."
OUTCOME=success
