import AppKit
import FrogCore
import XCTest
@testable import FrogApp

@MainActor
final class ClipboardHistoryTests: XCTestCase {
    func testOptInBoundsDuplicatesAndDisableClearsMemory() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.setString("Before opt-in", forType: .string)
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
        history.configure(enabled: true, automaticallyPoll: false)
        await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
        for index in 0..<102 {
            pasteboard.clearContents(); pasteboard.setString("Entry \(index)", forType: .string)
            await history.poll()
        }
        XCTAssertEqual(history.entries.map(\.text), (2..<102).reversed().map { "Entry \($0)" })
        pasteboard.clearContents(); pasteboard.setString("Entry 3", forType: .string)
        await history.poll()
        XCTAssertEqual(history.entries.count, 100)
        XCTAssertEqual(history.entries.first?.text, "Entry 3")
        XCTAssertEqual(history.entries.last?.text, "Entry 2")
        history.configure(enabled: false)
        XCTAssertTrue(history.entries.isEmpty)
        history.configure(enabled: true, automaticallyPoll: false)
        await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testFormattedAndUnformattedDelivery() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let rtf = Data("{\\rtf1\\ansi\\b Bold text}".utf8)
        let item = NSPasteboardItem()
        item.setString("Bold text", forType: .string); item.setData(rtf, forType: .rtf)
        item.setData(Data([1, 2, 3]), forType: .png)
        pasteboard.clearContents(); pasteboard.writeObjects([item])
        await history.poll()
        let entry = try XCTUnwrap(history.entries.first)
        XCTAssertEqual(entry.formatting, [NSPasteboard.PasteboardType.rtf.rawValue: rtf])
        XCTAssertTrue(entry.write(to: pasteboard, plainText: false))
        XCTAssertEqual(pasteboard.data(forType: .rtf), rtf)
        XCTAssertNil(pasteboard.data(forType: .png))
        XCTAssertTrue(entry.write(to: pasteboard, plainText: true))
        XCTAssertEqual(pasteboard.string(forType: .string), "Bold text")
        XCTAssertNil(pasteboard.data(forType: .rtf))
    }

    func testOversizedAndInternalCopiesAreExcludedButGeneratedTextIsIncluded() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let gate = ClipboardHistoryCaptureGate()
        let history = ClipboardHistoryStore(pasteboard: pasteboard, gate: gate)
        history.configure(enabled: true, automaticallyPoll: false)
        for marker in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            let item = NSPasteboardItem()
            item.setString("Sensitive text", forType: .string)
            item.setString("", forType: NSPasteboard.PasteboardType(marker))
            pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
        }
        XCTAssertEqual(history.entries.map(\.text), ["Sensitive text"])
        history.clear()
        pasteboard.clearContents(); pasteboard.setString(String(repeating: "x", count: 512 * 1024 + 1), forType: .string)
        await history.poll()
        gate.begin()
        pasteboard.clearContents(); pasteboard.setString("Internal selection", forType: .string)
        await history.poll()
        pasteboard.clearContents(); pasteboard.setString("Restored clipboard", forType: .string)
        gate.end(pasteboard: pasteboard)
        await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
        pasteboard.clearContents(); pasteboard.setString("User copy", forType: .string)
        await history.poll()
        XCTAssertEqual(history.entries.map(\.text), ["User copy"])
        history.clear(); await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
        history.configure(enabled: false)
    }

    func testConcealedTextIsRetainedInMemoryAndKeepsItsMarkerWhenCopied() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        defer { history.configure(enabled: false) }
        let item = NSPasteboardItem()
        item.setString("Synthetic secret", forType: .string)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
        XCTAssertEqual(history.entries.map(\.text), ["Synthetic secret"])
        if let entry = history.entries.first {
            XCTAssertTrue(entry.write(to: pasteboard, plainText: true))
            XCTAssertTrue(pasteboard.types?.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) == true)
        }
    }

    func testUserCopyImmediatelyAfterInternalRestorationIsNotDropped() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let gate = ClipboardHistoryCaptureGate()
        let history = ClipboardHistoryStore(pasteboard: pasteboard, gate: gate)
        history.configure(enabled: true, automaticallyPoll: false)
        gate.begin()
        pasteboard.clearContents(); pasteboard.setString("Restored internal clipboard", forType: .string)
        gate.end(pasteboard: pasteboard)
        pasteboard.clearContents(); pasteboard.setString("Immediate user copy", forType: .string)
        await history.poll()
        XCTAssertEqual(history.entries.map(\.text), ["Immediate user copy"])
        history.configure(enabled: false)
    }

    func testDelayedEmptyClipboardPlaceholderIsRetried() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        defer { history.configure(enabled: false) }
        pasteboard.declareTypes([.string], owner: nil)
        pasteboard.setString("", forType: .string)
        let count = pasteboard.changeCount
        await history.poll()
        XCTAssertTrue(history.entries.isEmpty)
        pasteboard.setString("Delayed text", forType: .string)
        XCTAssertEqual(pasteboard.changeCount, count)
        await history.poll()
        XCTAssertEqual(history.entries.map(\.text), ["Delayed text"])
    }

    func testLegacyDefaultsAndShortcutConflicts() throws {
        let configuration = try ConfigurationFile.decode(ConfigurationFile.encode(Configuration()))
        XCTAssertNil(configuration.preferences.workflowSettings.clipboardHistoryEnabled)
        XCTAssertEqual(configuration.preferences.workflowSettings.effectiveClipboardHistoryHotkey, Hotkey(keyCode: 9, modifiers: 768))
        var enabled = configuration
        var workflow = enabled.preferences.workflowSettings
        workflow.clipboardHistoryEnabled = true
        enabled.preferences.workflows = workflow
        enabled.rules = [Rule(name: "Conflict", instructions: "test", hotkey: workflow.effectiveClipboardHistoryHotkey)]
        XCTAssertThrowsError(try ConfigurationFile.validate(enabled))
        enabled.preferences.workflows?.clipboardHistoryEnabled = false
        XCTAssertNoThrow(try ConfigurationFile.validate(enabled))
    }

    func testPasteWaitsForReleaseAndCannotDeliverAfterDisable() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.setString("Unchanged", forType: .string)
        let target = TestPasteTarget()
        let entry = ClipboardHistoryEntry(text: "Chosen")
        var current = true
        do {
            try await ClipboardHistoryDelivery.paste(entry, plainText: true, pasteboard: pasteboard, target: target,
                isCurrent: { current }, waitForRelease: { current = false })
            XCTFail("A disabled operation must not write or paste")
        } catch is CancellationError { }
        XCTAssertEqual(pasteboard.string(forType: .string), "Unchanged")
        XCTAssertEqual(target.requests, 0)
        try await ClipboardHistoryDelivery.paste(entry, plainText: true, pasteboard: pasteboard, target: target,
            isCurrent: { true }, waitForRelease: {})
        XCTAssertEqual(target.requests, 1)
        XCTAssertEqual(pasteboard.string(forType: .string), "Chosen")
    }

    func testUnavailableOrChangedTargetLeavesCopyOnly() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let target = TestPasteTarget()
        target.changed = true
        for destination in [nil, target] as [(any ClipboardHistoryPasteTarget)?] {
            do {
                try await ClipboardHistoryDelivery.paste(ClipboardHistoryEntry(text: "Copy only"), plainText: false,
                    pasteboard: pasteboard, target: destination, isCurrent: { true }, waitForRelease: {})
                XCTFail("Unavailable targets must not receive a paste")
            } catch { XCTAssertFalse(error is CancellationError) }
            XCTAssertEqual(pasteboard.string(forType: .string), "Copy only")
        }
        XCTAssertEqual(target.requests, 0)
    }

    func testAppPreferencesRejectReservedClipboardShortcutAndPersistOnlySettings() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let model = AppModel(dataDirectory: directory, registerShortcuts: false)
        defer { model.shutdown() }
        var workflow = model.configuration.preferences.workflowSettings
        workflow.clipboardHistoryEnabled = true
        workflow.clipboardHistoryHotkey = Hotkey(keyCode: 9, modifiers: 256)
        XCTAssertThrowsError(try model.saveWorkflowPreferences(workflow))
        workflow.clipboardHistoryHotkey = nil
        try model.saveWorkflowPreferences(workflow)
        let saved = try ConfigurationStore(directory: directory).load()
        XCTAssertEqual(saved.preferences.workflowSettings.clipboardHistoryEnabled, true)
        XCTAssertEqual(saved.preferences.workflowSettings.effectiveClipboardHistoryHotkey, Hotkey(keyCode: 9, modifiers: 768))
        let exported = try ConfigurationFile.encode(saved)
        let decoded = try ConfigurationFile.decode(exported)
        XCTAssertEqual(decoded.preferences.workflowSettings, saved.preferences.workflowSettings)
        XCTAssertFalse(String(decoding: exported, as: UTF8.self).contains("\"formatting\""))
    }

    func testClipboardShortcutCanBeChangedBeforeEnablingWhenDefaultConflicts() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        var configuration = Configuration()
        configuration.rules = [Rule(name: "Existing", instructions: "test", hotkey: Hotkey(keyCode: 9, modifiers: 768))]
        try ConfigurationStore(directory: directory).save(configuration)
        let model = AppModel(dataDirectory: directory, registerShortcuts: false)
        defer { model.shutdown() }
        var workflow = model.configuration.preferences.workflowSettings
        workflow.clipboardHistoryHotkey = Hotkey(keyCode: 9, modifiers: 4608)
        try model.saveWorkflowPreferences(workflow)
        workflow.clipboardHistoryEnabled = true
        try model.saveWorkflowPreferences(workflow)
        XCTAssertEqual(model.configuration.rules.first?.hotkey, Hotkey(keyCode: 9, modifiers: 768))
        XCTAssertEqual(model.configuration.preferences.workflowSettings.effectiveClipboardHistoryHotkey, Hotkey(keyCode: 9, modifiers: 4608))
    }

    func testNativePanelKeyboardSelectionPlainPasteEscapeAndStop() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let target = TestPasteTarget()
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { target }, waitForRelease: {}, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        for text in ["First", "Second"] {
            let item = NSPasteboardItem()
            item.setString(text, forType: .string); item.setData(Data("{\\rtf1 \(text)}".utf8), forType: .rtf)
            pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
        }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        XCTAssertTrue(panel.styleMask.contains(.nonactivatingPanel))
        XCTAssertFalse(panel.canBecomeMain)
        try await sendKey(125, to: panel)
        try await sendKey(36, flags: .shift, to: panel)
        await controller.waitForDelivery()
        XCTAssertFalse(panel.isVisible)
        XCTAssertEqual(target.requests, 1)
        XCTAssertEqual(pasteboard.string(forType: .string), "First")
        XCTAssertNil(pasteboard.data(forType: .rtf))
        controller.show()
        let secondPanel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        try await sendKey(53, to: secondPanel)
        XCTAssertFalse(secondPanel.isVisible)
        XCTAssertEqual(target.requests, 1)
        controller.show(); controller.stop()
        XCTAssertTrue(history.entries.isEmpty)
        XCTAssertFalse(history.enabled)
        XCTAssertFalse(NSApplication.shared.windows.contains { $0.isVisible && $0.title == "Clipboard history" })
    }

    private func sendKey(_ code: UInt16, flags: NSEvent.ModifierFlags = [], to window: NSWindow) async throws {
        let event = try XCTUnwrap(NSEvent.keyEvent(with: .keyDown, location: .zero, modifierFlags: flags,
            timestamp: ProcessInfo.processInfo.systemUptime, windowNumber: window.windowNumber, context: nil,
            characters: "", charactersIgnoringModifiers: "", isARepeat: false, keyCode: code))
        NSApplication.shared.sendEvent(event)
        try await Task.sleep(for: .milliseconds(20))
    }

    func testCommandCCopiesSelectedHistoryItemWithoutPasting() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        history.recordCopiedText("Selected history text")
        pasteboard.clearContents(); pasteboard.setString("Current clipboard", forType: .string)
        let target = TestPasteTarget()
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history,
            captureTarget: { target }, waitForRelease: {}, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        try await sendKey(8, flags: .command, to: panel)
        XCTAssertEqual(pasteboard.string(forType: .string), "Selected history text")
        XCTAssertEqual(target.requests, 0)
    }

    func testCopyButtonWorksWithoutAnAutomaticPasteTarget() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        history.recordCopiedText("Copy from history")
        pasteboard.clearContents(); pasteboard.setString("Before", forType: .string)
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { nil },
            activationNotifications: NotificationCenter())
        defer { controller.stop() }
        controller.onError = { XCTFail($0.localizedDescription) }
        controller.show()
        try await Task.sleep(for: .milliseconds(50))
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        let view = try XCTUnwrap(panel.contentView)
        view.layoutSubtreeIfNeeded()
        let y = ClipboardHistoryLayout.headerHeight + 1 + ClipboardHistoryLayout.inset + ClipboardHistoryLayout.rowHeight / 2
        let point = view.convert(NSPoint(x: 384, y: view.isFlipped ? y : view.bounds.maxY - y), to: nil)
        for type in [NSEvent.EventType.leftMouseDown, .leftMouseUp] {
            NSApplication.shared.sendEvent(try XCTUnwrap(NSEvent.mouseEvent(with: type, location: point, modifierFlags: [],
                timestamp: ProcessInfo.processInfo.systemUptime, windowNumber: panel.windowNumber, context: nil,
                eventNumber: 0, clickCount: 1, pressure: 1)))
        }
        try await Task.sleep(for: .milliseconds(50))
        XCTAssertEqual(pasteboard.string(forType: .string), "Copy from history")
        XCTAssertFalse(panel.isVisible)
    }

    func testHundredEntriesStayCompactAndKeyboardScrollAndSearchReachOlderItems() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        for index in 0..<100 { history.recordCopiedText("Entry \(index)") }
        let target = TestPasteTarget()
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history,
            captureTarget: { target }, waitForRelease: {}, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        XCTAssertLessThan(panel.frame.height, 460)
        for _ in 0..<90 { try await sendKey(125, to: panel) }
        let scroll = try XCTUnwrap(descendants(try XCTUnwrap(panel.contentView)).compactMap { $0 as? NSScrollView }
            .first { ($0.documentView?.bounds.height ?? 0) > $0.bounds.height })
        XCTAssertGreaterThan(scroll.documentVisibleRect.minY, 0, "Keyboard selection must scroll to older entries")
        try await sendKey(36, to: panel)
        await controller.waitForDelivery()
        XCTAssertEqual(pasteboard.string(forType: .string), "Entry 9")
        XCTAssertEqual(target.requests, 1)
        controller.show()
        let searchPanel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        controller.state.query = "Entry 42"
        try await Task.sleep(for: .milliseconds(50))
        XCTAssertEqual(searchPanel.frame.size, ClipboardHistoryLayout.size(entryCount: 1))
        try await sendKey(36, to: searchPanel)
        await controller.waitForDelivery()
        XCTAssertEqual(pasteboard.string(forType: .string), "Entry 42")
        XCTAssertEqual(target.requests, 2)
    }

    private func descendants(_ view: NSView) -> [NSView] { [view] + view.subviews.flatMap(descendants) }

    func testNativePanelShowsFiveEntries() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        for text in ["Meeting notes — review the proposal on Monday.", "A longer copied paragraph that should fit into two lines and still leave room for both paste actions without making the panel grow.", "日本語のテキスト · café · 👨‍👩‍👧‍👦", "The quick brown fox jumps over the lazy dog.", "Hello, clipboard!"] {
            pasteboard.clearContents(); pasteboard.setString(text, forType: .string); await history.poll()
        }
        controller.show()
        try await Task.sleep(for: .milliseconds(50))
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        let view = try XCTUnwrap(panel.contentView)
        view.layoutSubtreeIfNeeded()
        XCTAssertEqual(history.entries.count, 5)
        XCTAssertEqual(view.bounds.size, ClipboardHistoryLayout.size(entryCount: 5))
        if let path = ProcessInfo.processInfo.environment["FROG_TEST_CLIPBOARD_SNAPSHOT"] {
            let bitmap = try XCTUnwrap(view.bitmapImageRepForCachingDisplay(in: view.bounds))
            view.cacheDisplay(in: view.bounds, to: bitmap)
            try XCTUnwrap(bitmap.representation(using: .png, properties: [:])).write(to: URL(fileURLWithPath: path))
        }
    }

    func testPanelResizesWithEntriesAndOnlySensitiveItemsReveal() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        history.recordCopiedText("Ordinary copied text")
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        XCTAssertEqual(panel.frame.size, ClipboardHistoryLayout.size(entryCount: 1))
        XCTAssertEqual(history.entries.first?.displayPreview(revealed: false), "Ordinary copied text")
        try await sendKey(49, to: panel)
        XCTAssertTrue(controller.state.revealedIDs.isEmpty, "Space must not disguise ordinary text as a password")
        let sensitive = NSPasteboardItem()
        sensitive.setString("Synthetic secret", forType: .string)
        sensitive.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.clearContents(); pasteboard.writeObjects([sensitive]); await history.poll()
        try await Task.sleep(for: .milliseconds(30))
        let entry = try XCTUnwrap(history.entries.first)
        XCTAssertEqual(panel.frame.size, ClipboardHistoryLayout.size(entryCount: 2))
        XCTAssertFalse(entry.displayPreview(revealed: false).contains("Synthetic secret"))
        try await sendKey(49, to: panel)
        XCTAssertEqual(controller.state.revealedIDs, [entry.id])
        history.clear()
        try await Task.sleep(for: .milliseconds(30))
        XCTAssertEqual(panel.frame.size, ClipboardHistoryLayout.size(entryCount: 0))
        XCTAssertTrue(controller.state.revealedIDs.isEmpty)
    }

    func testCompactPanelRendersMixedSensitiveAndFormattedEntriesInLightAndDarkThemes() async throws {
        _ = NSApplication.shared
        let previous = FrogAppearance.shared.settings
        defer { FrogAppearance.shared.apply(previous) }
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        for text in ["Meeting notes — review the proposal on Monday.", "日本語のテキスト · café · 👨‍👩‍👧‍👦", "A longer copied paragraph wraps to two lines while keeping both compact paste actions visible."] {
            history.recordCopiedText(text)
        }
        let formatted = NSPasteboardItem()
        formatted.setString("Copied transcription with formatting", forType: .string)
        formatted.setData(Data("<b>Copied transcription with formatting</b>".utf8), forType: .html)
        pasteboard.clearContents(); pasteboard.writeObjects([formatted]); await history.poll()
        let sensitive = NSPasteboardItem()
        sensitive.setString("Synthetic concealed fixture", forType: .string)
        sensitive.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.clearContents(); pasteboard.writeObjects([sensitive]); await history.poll()
        for dark in [false, true] {
            var appearance = previous
            appearance.mode = dark ? .dark : .light
            appearance.theme = dark ? .tokyoNight : .frog
            appearance.useThemeAccent = true
            FrogAppearance.shared.apply(appearance)
            controller.show()
            try await Task.sleep(for: .milliseconds(50))
            let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
            let view = try XCTUnwrap(panel.contentView)
            view.layoutSubtreeIfNeeded()
            XCTAssertEqual(view.bounds.size, ClipboardHistoryLayout.size(entryCount: 5))
            XCTAssertTrue(controller.state.revealedIDs.isEmpty)
            if let root = ProcessInfo.processInfo.environment["FROG_TEST_COMPACT_CLIPBOARD_SNAPSHOT"] {
                let bitmap = try XCTUnwrap(view.bitmapImageRepForCachingDisplay(in: view.bounds))
                view.cacheDisplay(in: view.bounds, to: bitmap)
                try XCTUnwrap(bitmap.representation(using: .png, properties: [:])).write(to: URL(fileURLWithPath: root + (dark ? "-dark.png" : "-light.png")))
            }
            controller.hide()
        }
    }

    func testCompactPasteIconActionsDeliverFormattedAndPlainText() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let item = NSPasteboardItem()
        item.setString("Formatted fixture", forType: .string)
        item.setData(Data("<b>Formatted fixture</b>".utf8), forType: .html)
        pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
        let target = TestPasteTarget()
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { target },
            waitForRelease: {}, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        for plain in [false, true] {
            pasteboard.clearContents(); pasteboard.setString("Before choosing", forType: .string)
            controller.show()
            try await Task.sleep(for: .milliseconds(30))
            let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
            let view = try XCTUnwrap(panel.contentView)
            view.layoutSubtreeIfNeeded()
            let y = ClipboardHistoryLayout.headerHeight + 1 + ClipboardHistoryLayout.inset + ClipboardHistoryLayout.rowHeight / 2
            let point = view.convert(NSPoint(x: plain ? 452 : 418, y: view.isFlipped ? y : view.bounds.maxY - y), to: nil)
            for type in [NSEvent.EventType.leftMouseDown, .leftMouseUp] {
                let event = try XCTUnwrap(NSEvent.mouseEvent(with: type, location: point, modifierFlags: [], timestamp: ProcessInfo.processInfo.systemUptime,
                    windowNumber: panel.windowNumber, context: nil, eventNumber: 0, clickCount: 1, pressure: 1))
                NSApplication.shared.sendEvent(event)
                try await Task.sleep(for: .milliseconds(20))
            }
            await controller.waitForDelivery()
            XCTAssertEqual(target.requests, plain ? 2 : 1)
            XCTAssertEqual(pasteboard.string(forType: .string), "Formatted fixture")
            XCTAssertEqual(pasteboard.data(forType: .html) == nil, plain)
        }
    }

    func testAppActivationInvalidatesPasteWhileModifiersAreHeld() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        pasteboard.clearContents(); pasteboard.setString("Chosen", forType: .string); await history.poll()
        pasteboard.clearContents(); pasteboard.setString("Unchanged", forType: .string)
        let target = TestPasteTarget()
        var release: CheckedContinuation<Void, Never>?
        let paused = expectation(description: "Waiting for shortcut modifiers")
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { target },
            waitForRelease: { await withCheckedContinuation { release = $0; paused.fulfill() } })
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        try await sendKey(36, to: panel)
        await fulfillment(of: [paused], timeout: 1)
        let finished = Task { await controller.waitForDelivery() }
        await Task.yield()
        NSWorkspace.shared.notificationCenter.post(name: NSWorkspace.didActivateApplicationNotification, object: nil)
        release?.resume()
        await finished.value
        XCTAssertEqual(target.requests, 0)
        XCTAssertEqual(pasteboard.string(forType: .string), "Unchanged")
    }

    func testReopeningDuringPendingPasteDoesNotAccumulateActivationObservers() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        pasteboard.clearContents(); pasteboard.setString("Chosen", forType: .string); await history.poll()
        var release: CheckedContinuation<Void, Never>?
        let target = TestPasteTarget()
        let notifications = CountingNotificationCenter()
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { target },
            waitForRelease: { await withCheckedContinuation { release = $0 } }, activationNotifications: notifications)
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        XCTAssertEqual(notifications.observerCount, 1)
        try await sendKey(36, to: panel)
        let finished = Task { await controller.waitForDelivery() }
        await Task.yield()
        controller.show()
        XCTAssertEqual(notifications.observerCount, 1, "Reopening must replace, not leak, the pending delivery observer")
        release?.resume()
        await finished.value
        XCTAssertEqual(target.requests, 0)
        controller.hide()
        XCTAssertEqual(notifications.observerCount, 0)
    }

    func testNativePanelClickAndSpaceRevealOnlyUntilPanelCloses() async throws {
        _ = NSApplication.shared
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let history = ClipboardHistoryStore(pasteboard: pasteboard)
        history.configure(enabled: true, automaticallyPoll: false)
        let item = NSPasteboardItem()
        item.setString("Synthetic private text", forType: .string)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
        let entry = try XCTUnwrap(history.entries.first)
        let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, activationNotifications: NotificationCenter())
        defer { controller.stop() }
        controller.show()
        let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
        XCTAssertTrue(controller.state.revealedIDs.isEmpty)
        try await sendKey(49, to: panel)
        XCTAssertEqual(controller.state.revealedIDs, [entry.id])
        try await sendKey(49, to: panel)
        XCTAssertTrue(controller.state.revealedIDs.isEmpty)
        let view = try XCTUnwrap(panel.contentView)
        view.layoutSubtreeIfNeeded()
        let rowCenter = ClipboardHistoryLayout.headerHeight + 1 + ClipboardHistoryLayout.inset + ClipboardHistoryLayout.rowHeight / 2
        let point = view.convert(NSPoint(x: 100, y: view.isFlipped ? rowCenter : view.bounds.maxY - rowCenter), to: nil)
        for type in [NSEvent.EventType.leftMouseDown, .leftMouseUp] {
            let event = try XCTUnwrap(NSEvent.mouseEvent(with: type, location: point, modifierFlags: [], timestamp: ProcessInfo.processInfo.systemUptime,
                windowNumber: panel.windowNumber, context: nil, eventNumber: 0, clickCount: 1, pressure: 1))
            NSApplication.shared.sendEvent(event)
            try await Task.sleep(for: .milliseconds(20))
        }
        try await Task.sleep(for: .milliseconds(20))
        XCTAssertTrue(panel.isVisible, "Clicking a copied-text preview must not dismiss the nonactivating panel")
        XCTAssertEqual(controller.state.revealedIDs, [entry.id])
        try await sendKey(53, to: panel)
        XCTAssertTrue(controller.state.revealedIDs.isEmpty)
        controller.show()
        XCTAssertTrue(controller.state.revealedIDs.isEmpty)
        XCTAssertEqual(history.entries.map(\.text), [entry.text])
    }

    func testRemovalDuringPendingPasteInvalidatesDeliveryAndStaleCopies() async throws {
        _ = NSApplication.shared
        for removal in ["clear", "evict", "replace"] {
            let pasteboard = NSPasteboard.withUniqueName()
            defer { pasteboard.releaseGlobally() }
            let history = ClipboardHistoryStore(pasteboard: pasteboard)
            history.configure(enabled: true, automaticallyPoll: false)
            pasteboard.clearContents(); pasteboard.setString("Chosen private text", forType: .string); await history.poll()
            let entry = try XCTUnwrap(history.entries.first)
            pasteboard.clearContents(); pasteboard.setString("Unchanged", forType: .string)
            var release: CheckedContinuation<Void, Never>?
            let target = TestPasteTarget()
            let controller = ClipboardHistoryController(pasteboard: pasteboard, history: history, captureTarget: { target },
                waitForRelease: { await withCheckedContinuation { release = $0 } }, activationNotifications: NotificationCenter())
            defer { controller.stop() }
            controller.show()
            let panel = try XCTUnwrap(NSApplication.shared.windows.first { $0.isVisible && $0.title == "Clipboard history" })
            try await sendKey(36, to: panel)
            let finished = Task { await controller.waitForDelivery() }
            for _ in 0..<100 where release == nil { await Task.yield() }
            let suspended = try XCTUnwrap(release, "Delivery must reach the modifier-release wait before removing the item")
            switch removal {
            case "clear": history.clear()
            case "evict":
                for index in 0..<100 {
                    pasteboard.clearContents(); pasteboard.setString("New fixture \(index)", forType: .string); await history.poll()
                }
            default:
                let item = NSPasteboardItem()
                item.setString(entry.text, forType: .string)
                item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
                pasteboard.clearContents(); pasteboard.writeObjects([item]); await history.poll()
            }
            pasteboard.clearContents(); pasteboard.setString("Unchanged", forType: .string)
            suspended.resume(); await finished.value
            XCTAssertEqual(target.requests, 0, removal)
            XCTAssertEqual(pasteboard.string(forType: .string), "Unchanged", removal)
            XCTAssertFalse(history.copy(entry), removal)
            XCTAssertEqual(pasteboard.string(forType: .string), "Unchanged", removal)
        }
    }
}

private final class CountingNotificationCenter: NotificationCenter, @unchecked Sendable {
    private let lock = NSLock()
    private var tokens = Set<ObjectIdentifier>()
    var observerCount: Int { lock.lock(); defer { lock.unlock() }; return tokens.count }
    override func addObserver(forName name: NSNotification.Name?, object obj: Any?, queue: OperationQueue?,
                              using block: @Sendable @escaping (Notification) -> Void) -> NSObjectProtocol {
        let token = super.addObserver(forName: name, object: obj, queue: queue, using: block)
        lock.lock(); tokens.insert(ObjectIdentifier(token)); lock.unlock()
        return token
    }
    override func removeObserver(_ observer: Any) {
        lock.lock(); tokens.remove(ObjectIdentifier(observer as AnyObject)); lock.unlock()
        super.removeObserver(observer)
    }
}

@MainActor
private final class TestPasteTarget: ClipboardHistoryPasteTarget {
    var requests = 0
    var changed = false
    func paste() throws {
        if changed { throw FrogError.message("Target changed") }
        requests += 1
    }
}
