// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteLocalModel(arg1) {
  return window['go']['main']['App']['DeleteLocalModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function DownloadModelFromURL(arg1, arg2) {
  return window['go']['main']['App']['DownloadModelFromURL'](arg1, arg2);
}

export function ExecuteShortcut(arg1) {
  return window['go']['main']['App']['ExecuteShortcut'](arg1);
}

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function GetActiveProviderName() {
  return window['go']['main']['App']['GetActiveProviderName']();
}

export function GetAllDownloadStatuses() {
  return window['go']['main']['App']['GetAllDownloadStatuses']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadStatus(arg1) {
  return window['go']['main']['App']['GetDownloadStatus'](arg1);
}

export function GetGlobalHotkeys() {
  return window['go']['main']['App']['GetGlobalHotkeys']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetLocalModels() {
  return window['go']['main']['App']['GetLocalModels']();
}

export function GetServerError() {
  return window['go']['main']['App']['GetServerError']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function GetTextProcessingConfig() {
  return window['go']['main']['App']['GetTextProcessingConfig']();
}

export function InstallBinary() {
  return window['go']['main']['App']['InstallBinary']();
}

export function IsBinaryInstalled() {
  return window['go']['main']['App']['IsBinaryInstalled']();
}

export function IsModelDownloaded(arg1) {
  return window['go']['main']['App']['IsModelDownloaded'](arg1);
}

export function IsServerReady() {
  return window['go']['main']['App']['IsServerReady']();
}

export function ListInstalledApps() {
  return window['go']['main']['App']['ListInstalledApps']();
}

export function OpenApplication(arg1, arg2) {
  return window['go']['main']['App']['OpenApplication'](arg1, arg2);
}

export function PasteBelowCursor(arg1) {
  return window['go']['main']['App']['PasteBelowCursor'](arg1);
}

export function ProcessText(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessText'](arg1, arg2, arg3);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReplaceSelectedText(arg1) {
  return window['go']['main']['App']['ReplaceSelectedText'](arg1);
}

export function SaveAction(arg1) {
  return window['go']['main']['App']['SaveAction'](arg1);
}

export function SaveGlobalHotkeys(arg1) {
  return window['go']['main']['App']['SaveGlobalHotkeys'](arg1);
}

export function SaveLLMConfig(arg1) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1);
}

export function SaveShortcuts(arg1) {
  return window['go']['main']['App']['SaveShortcuts'](arg1);
}

export function SaveTextProcessingConfig(arg1) {
  return window['go']['main']['App']['SaveTextProcessingConfig'](arg1);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function StopLocalServer() {
  return window['go']['main']['App']['StopLocalServer']();
}
