// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {llm} from '../models';
import {shortcuts} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteLocalModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function DownloadModelFromURL(arg1:string,arg2:string):Promise<void>;

export function ExecuteShortcut(arg1:string):Promise<void>;

export function GetActions():Promise<Array<config.ActionConfig>>;

export function GetActiveProviderName():Promise<string>;

export function GetAllDownloadStatuses():Promise<Array<llm.DownloadStatus>>;

export function GetAvailableModels():Promise<Array<llm.ModelEntry>>;

export function GetClipboardText():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetDownloadStatus(arg1:string):Promise<llm.DownloadStatus>;

export function GetGlobalHotkeys():Promise<Array<config.GlobalHotkeyConfig>>;

export function GetLLMConfig():Promise<config.LLMConfig>;

export function GetLocalModels():Promise<Array<llm.LocalModel>>;

export function GetServerError():Promise<string>;

export function GetServerLogs():Promise<Array<string>>;

export function GetServerStatus():Promise<llm.ServerStatus>;

export function GetShortcuts():Promise<Array<config.ShortcutConfig>>;

export function GetTextProcessingConfig():Promise<config.TextProcessingConfig>;

export function InstallBinary():Promise<void>;

export function IsBinaryInstalled():Promise<boolean>;

export function IsModelDownloaded(arg1:string):Promise<boolean>;

export function IsServerReady():Promise<boolean>;

export function ListInstalledApps():Promise<Array<shortcuts.AppInfo>>;

export function OpenApplication(arg1:string,arg2:string):Promise<void>;

export function PasteBelowCursor(arg1:string):Promise<void>;

export function ProcessText(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function Quit():Promise<void>;

export function ReplaceSelectedText(arg1:string):Promise<void>;

export function SaveAction(arg1:config.ActionConfig):Promise<void>;

export function SaveGlobalHotkeys(arg1:Array<config.GlobalHotkeyConfig>):Promise<void>;

export function SaveLLMConfig(arg1:config.LLMConfig):Promise<void>;

export function SaveShortcuts(arg1:Array<config.ShortcutConfig>):Promise<void>;

export function SaveTextProcessingConfig(arg1:config.TextProcessingConfig):Promise<void>;

export function SetActiveModel(arg1:string):Promise<void>;

export function SetClipboardText(arg1:string):Promise<void>;

export function StopLocalServer():Promise<void>;
